spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
         search-locations: "file:///C://Users//kh715e//Desktop//Work//LEARNING_2024//Microservices//UDEMY_COURSE//config"

server:
  port: 8071
